# This file is partially auto-generated by `nixos-generate-config`
# wrapped in configurations.nixos.<host>.module. Drop the
# `not-detected.nix` import as it triggers infinite recursion in
# the checks done by ../../configurations/nixos.nix.
{
  lib,
  ...
}:
{
  configurations.nixos.halflight.module =
    { config, ... }:
    {
      # Added this line due to breaking after removing not-detected
      hardware.enableRedistributableFirmware = true;

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/88eb33a6-a638-45fe-9468-dc684af24025";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/45C5-25E3";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/a75f5134-b615-479c-b405-990dfc92f3bb"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
