# This file is partially auto-generated by `nixos-generate-config`
# wrapped in configurations.nixos.<host>.module. Drop the
# `not-detected.nix` import as it triggers infinite recursion in
# the checks done by ../../configurations/nixos.nix.
{
  lib,
  ...
}:
{
  configurations.nixos.halflight.module =
    { config, ... }:
    {
      # Added this line due to breaking after removing not-detected
      hardware.enableRedistributableFirmware = true;

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      # FILL IN: UUID of the LUKS partition (the crypto_LUKS one, e.g. nvme0n1p2).
      #   blkid | grep crypto_LUKS
      boot.initrd.luks.devices."cryptroot" = {
        device = "/dev/disk/by-uuid/REPLACE-LUKS-PART-UUID";
        crypttabExtraOpts = [ "fido2-device=auto" ];
      };

      fileSystems."/" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=root" "compress=zstd" "noatime" ];
      };

      fileSystems."/nix" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=nix" "compress=zstd" "noatime" ];
      };

      fileSystems."/persist" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        neededForBoot = true;
        options = [ "subvol=persist" "compress=zstd" "noatime" ];
      };

      fileSystems."/home" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=home" "compress=zstd" "noatime" ];
      };

      # FILL IN: UUID of the ESP (the vfat boot partition, e.g. nvme0n1p1).
      #   blkid | grep vfat
      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/REPLACE-ESP-UUID";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

      swapDevices = [ ];
      zramSwap.enable = true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
