# This file is partially auto-generated by `nixos-generate-config`
# wrapped in configurations.nixos.<host>.module. Drop the
# `not-detected.nix` import as it triggers infinite recursion in
# the checks done by ../../configurations/nixos.nix.
{
  lib,
  ...
}:
{
  configurations.nixos.lazarus.module =
    { config, ... }:
    {
      hardware.enableRedistributableFirmware = true;

      boot.initrd.availableKernelModules = [
        "nvme"
        "ahci"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      boot.initrd.luks.devices."cryptroot" = {
        device = "/dev/disk/by-partlabel/cryptroot";
        crypttabExtraOpts = [ "fido2-device=auto" ];
      };

      fileSystems."/" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=root" "compress=zstd" "noatime" ];
      };

      fileSystems."/nix" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=nix" "compress=zstd" "noatime" ];
      };

      fileSystems."/persist" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        neededForBoot = true;
        options = [ "subvol=persist" "compress=zstd" "noatime" ];
      };

      fileSystems."/home" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=home" "compress=zstd" "noatime" ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-partlabel/ESP";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

      swapDevices = [ ];
      zramSwap.enable = true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
