# This file is partially auto-generated by `nixos-generate-config`
# wrapped in configurations.nixos.<host>.module. Drop the
# `not-detected.nix` import as it triggers infinite recursion in
# the checks done by ../../configurations/nixos.nix.
{
  lib,
  ...
}:
{
  configurations.nixos.lazarus.module =
    { config, ... }:
    {

      boot.initrd.availableKernelModules = [
        "nvme"
        "ahci"
        "xhci_pci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/195cc87a-0546-46ee-ba1c-8c1d0c20898d";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/E41D-DFD5";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/8668e252-4f98-4fa0-b813-d7ca9a10794f"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
